Bump frontside/eslint-config and remove redundant typescript devdep
thefrontside/effection pull request #172
Opened 2020-07-06 19:45 UTC by minkimcello

## Approach
- Upgraded `@frontside/eslint-config` from `v1.0.0` to `v1.1.0` which comes prepacked with:
  - `@typescript-eslint/eslint-plugin`
  - `@typescript-eslint/parser`
  - `eslint`
  - `eslint-plugin-prefer-let`
  - `typescript`
- With the exception of `packages/effection` (because it's in JS and not TS), I went down the list of packages and removed duplicate dependencies; which in this case was just `typescript`.

2020-07-06 20:02 UTC, cowboyd commented
Why is typescript a duplicate dependency? Does `tsdx` depend on it explicitly?

2020-07-06 20:19 UTC, minkimcello commented
@cowboyd I'm not sure `tsdx` depends on it but `eslint-config` comes with `typescript` whether we need it or not so I was able to remove it from the individual packages. It still builds fine using `tsdx`.

2020-07-07 14:49 UTC, cowboyd commented
Even though our `eslint-config` depends on typescript, and so some version of the typescript compiler will be in the project, it's not a good practice to rely on implicit dependencies when your need is explicit. The heuristic should be, "if I removed `@frontside/eslint-config` from my dependencies, can I guarantee my project continue to work otherwise?" In this case, our code is in typescript, and so the answer is no. 

Our code is in typescript, and so we therefor have a primary dependency on packages whose contract is to provide the typescript compiler.

What could work, if we want to optimize our dependencies is to create a `@frontside/typescript` package which provides typescript _and_ `@frontside/eslint-config` as part of its publicly stated contract.

2020-07-07 15:37 UTC, minkimcello commented
@cowboyd Oh I see. That makes sense. Should I have named `frontside/eslint-config` to `frontside/eslint` if we're providing `eslint` within `eslint-config`? Or maybe I should not have added `eslint` and `typescript` as dependencies to `eslint-config`?

2020-07-08 16:12 UTC, cowboyd requested changes
Each package should have the things it needs to build in its dependencies, not inherit them from the ambient environment.

2020-07-08 16:12 UTC, cowboyd commented on package.json
> +    "typescript": "^3.9.5"
I don't think we need typescript in the root

2020-07-08 18:12 UTC, cowboyd commented
We shouldn't have `eslint` at the root of the repo either.

2020-07-08 20:34 UTC, minkimcello commented
So generally do we keep devDependencies in its own package and only bring dependencies to the root if all packages utilize it?

Should I add `eslint` to every package? It was only in `packages/effection`.

2020-07-09 15:27 UTC, cowboyd commented
> So generally do we keep devDependencies in its own package and only bring dependencies to the root if all packages utilize it?

We should never bring dependencies to the root.

As for `eslint`, yes, let's add it to just `effection`

2020-07-09 15:36 UTC, minkimcello commented
> We should never bring dependencies to the root.

What about dev dependencies? We have devDeps at the root of both effection and bigtest monorepos.

> As for `eslint`, yes, let's add it to just `effection`

Why is it okay for `eslint` to only be in `packages/effection` when every package runs eslint script?

2020-07-09 17:38 UTC, cowboyd commented
> Why is it okay for eslint to only be in packages/effection when every package runs eslint script?

Oh, I thought you said that only `effection` used `eslint`. Every package that uses `eslint` should have it as a dependency.

2020-07-13 17:09 UTC, cowboyd approved these changes

2020-07-13 17:09 UTC, merged