Version Packages (preview)
thefrontside/effection pull request #263
Opened 2021-03-13 14:56 UTC by frontsidejack

This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to v2, this PR will be updated.

⚠️⚠️⚠️⚠️⚠️⚠️

`v2` is currently in **pre mode** so this branch has prereleases rather than normal releases. If you want to exit prereleases, run `changeset pre exit` on `v2`.

⚠️⚠️⚠️⚠️⚠️⚠️

# Releases
## effection@2.0.0-preview.6

### Minor Changes

-   2c2749d: Add a `buffer` method on Stream to buffer stream contents for later replay

### Patch Changes

-   Updated dependencies [2c2749d]
    -   @effection/subscription@2.0.0-preview.5

 ## @effection/subscription@2.0.0-preview.5

### Minor Changes

-   2c2749d: Add a `buffer` method on Stream to buffer stream contents for later replay

2021-03-15 17:09 UTC, minkimcello requested changes
We need to merge #267 first.

2021-03-18 09:09 UTC, cowboyd commented
@minkimcello #267 is merged. Does that mean this is a go?

2021-03-18 12:31 UTC, minkimcello approved these changes

2021-03-24 13:18 UTC, jnicklas requested changes

2021-03-24 13:18 UTC, jnicklas commented on packages/fetch/package.json
> +  "version": "1.0.0-preview.5",
This is broken again

2021-03-24 13:18 UTC, jnicklas commented on packages/atom/package.json
> +  "version": "2.0.0-preview.3-preview.4",
What happened here?

2021-03-25 08:22 UTC, cowboyd commented on packages/atom/package.json
> +  "version": "2.0.0-preview.3-preview.4",
Whoa!

2021-03-25 09:57 UTC, jnicklas approved these changes

2021-03-25 09:59 UTC, cowboyd approved these changes

2021-03-25 10:00 UTC, cowboyd approved these changes

2021-03-25 12:08 UTC, merged